"""initial schema

Revision ID: 6e673b84aad2
Revises: 
Create Date: 2026-08-08 22:42:18.738111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e673b84aad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_canonical', sa.String(), nullable=False),
    sa.Column('company_display', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_derived', sa.String(), nullable=False),
    sa.Column('human_engaged', sa.Boolean(), nullable=False),
    sa.Column('notion_page_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_company_canonical'), 'applications', ['company_canonical'], unique=False)
    op.create_table('emails',
    sa.Column('gmail_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('from_addr', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('gmail_id')
    )
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_table('failed_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('parked', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_jobs_email_id'), 'failed_jobs', ['email_id'], unique=False)
    op.create_table('sync_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.gmail_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_email_id'), 'classifications', ['email_id'], unique=False)
    op.create_table('eval_labels',
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('true_category', sa.String(), nullable=False),
    sa.Column('true_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.gmail_id'], ),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['emails.gmail_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_application_id'), 'events', ['application_id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_confidence', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('effort_minutes', sa.Integer(), nullable=False),
    sa.Column('next_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_tier', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_application_id'), 'obligations', ['application_id'], unique=False)
    op.create_index(op.f('ix_obligations_next_alert_at'), 'obligations', ['next_alert_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obligation_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slack_ts', sa.String(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('marked_junk', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_obligation_id'), 'alerts', ['obligation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_obligation_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_obligations_next_alert_at'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_application_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_events_application_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('eval_labels')
    op.drop_index(op.f('ix_classifications_email_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_failed_jobs_email_id'), table_name='failed_jobs')
    op.drop_table('failed_jobs')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_applications_company_canonical'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
